title: TitaniumSrc
description: TitaniumSrc Game Engine
domain: titaniumsrc.github.io
url: https://titaniumsrc.github.io
baseurl: /
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
